package DanKrauseUnitTesting;

import edu.coolschool.utilities.CountriesEnum;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class DanKrauseCountriesTesting {

    @Test
    @DisplayName("Test All Display Names")
    public void countriesTestingTestAllDisplayNames() {
        assertEquals("Afghanistan", CountriesEnum.AF.getDisplayName());
        assertEquals("Albania", CountriesEnum.AL.getDisplayName());
        assertEquals("Algeria", CountriesEnum.DZ.getDisplayName());
        assertEquals("Andorra", CountriesEnum.AD.getDisplayName());
        assertEquals("Angola", CountriesEnum.AO.getDisplayName());
        assertEquals("Antigua and Barbuda", CountriesEnum.AG.getDisplayName());
        assertEquals("Argentina", CountriesEnum.AR.getDisplayName());
        assertEquals("Armenia", CountriesEnum.AM.getDisplayName());
        assertEquals("Australia", CountriesEnum.AU.getDisplayName());
        assertEquals("Austria", CountriesEnum.AT.getDisplayName());
        assertEquals("Azerbaijan", CountriesEnum.AZ.getDisplayName());
        assertEquals("Bahamas", CountriesEnum.BS.getDisplayName());
        assertEquals("Bahrain", CountriesEnum.BH.getDisplayName());
        assertEquals("Bangladesh", CountriesEnum.BD.getDisplayName());
        assertEquals("Barbados", CountriesEnum.BB.getDisplayName());
        assertEquals("Belarus", CountriesEnum.BY.getDisplayName());
        assertEquals("Belgium", CountriesEnum.BE.getDisplayName());
        assertEquals("Belize", CountriesEnum.BZ.getDisplayName());
        assertEquals("Benin", CountriesEnum.BJ.getDisplayName());
        assertEquals("Bhutan", CountriesEnum.BT.getDisplayName());
        assertEquals("Bolivia", CountriesEnum.BO.getDisplayName());
        assertEquals("Bosnia and Herzegovina", CountriesEnum.BA.getDisplayName());
        assertEquals("Botswana", CountriesEnum.BW.getDisplayName());
        assertEquals("Brazil", CountriesEnum.BR.getDisplayName());
        assertEquals("Brunei", CountriesEnum.BN.getDisplayName());
        assertEquals("Bulgaria", CountriesEnum.BG.getDisplayName());
        assertEquals("Burkina Faso", CountriesEnum.BF.getDisplayName());
        assertEquals("Burundi", CountriesEnum.BI.getDisplayName());
        assertEquals("Cabo Verde", CountriesEnum.CV.getDisplayName());
        assertEquals("Cambodia", CountriesEnum.KH.getDisplayName());
        assertEquals("Cameroon", CountriesEnum.CM.getDisplayName());
        assertEquals("Canada", CountriesEnum.CA.getDisplayName());
        assertEquals("Central African Republic", CountriesEnum.CF.getDisplayName());
        assertEquals("Chad", CountriesEnum.TD.getDisplayName());
        assertEquals("Chile", CountriesEnum.CL.getDisplayName());
        assertEquals("China", CountriesEnum.CN.getDisplayName());
        assertEquals("Colombia", CountriesEnum.CO.getDisplayName());
        assertEquals("Comoros", CountriesEnum.KM.getDisplayName());
        assertEquals("Congo - Brazzaville", CountriesEnum.CG.getDisplayName());
        assertEquals("Congo - Kinshasa", CountriesEnum.CD.getDisplayName());
        assertEquals("Costa Rica", CountriesEnum.CR.getDisplayName());
        assertEquals("Côte d'Ivoire", CountriesEnum.CI.getDisplayName());
        assertEquals("Croatia", CountriesEnum.HR.getDisplayName());
        assertEquals("Cuba", CountriesEnum.CU.getDisplayName());
        assertEquals("Cyprus", CountriesEnum.CY.getDisplayName());
        assertEquals("Czechia", CountriesEnum.CZ.getDisplayName());
        assertEquals("Denmark", CountriesEnum.DK.getDisplayName());
        assertEquals("Djibouti", CountriesEnum.DJ.getDisplayName());
        assertEquals("Dominica", CountriesEnum.DM.getDisplayName());
        assertEquals("Dominican Republic", CountriesEnum.DO.getDisplayName());
        assertEquals("Ecuador", CountriesEnum.EC.getDisplayName());
        assertEquals("Egypt", CountriesEnum.EG.getDisplayName());
        assertEquals("El Salvador", CountriesEnum.SV.getDisplayName());
        assertEquals("Equatorial Guinea", CountriesEnum.GQ.getDisplayName());
        assertEquals("Eritrea", CountriesEnum.ER.getDisplayName());
        assertEquals("Estonia", CountriesEnum.EE.getDisplayName());
        assertEquals("Eswatini", CountriesEnum.SZ.getDisplayName());
        assertEquals("Ethiopia", CountriesEnum.ET.getDisplayName());
        assertEquals("Fiji", CountriesEnum.FJ.getDisplayName());
        assertEquals("Finland", CountriesEnum.FI.getDisplayName());
        assertEquals("France", CountriesEnum.FR.getDisplayName());
        assertEquals("Gabon", CountriesEnum.GA.getDisplayName());
        assertEquals("Gambia", CountriesEnum.GM.getDisplayName());
        assertEquals("Georgia", CountriesEnum.GE.getDisplayName());
        assertEquals("Germany", CountriesEnum.DE.getDisplayName());
        assertEquals("Ghana", CountriesEnum.GH.getDisplayName());
        assertEquals("Greece", CountriesEnum.GR.getDisplayName());
        assertEquals("Grenada", CountriesEnum.GD.getDisplayName());
        assertEquals("Guatemala", CountriesEnum.GT.getDisplayName());
        assertEquals("Guinea", CountriesEnum.GN.getDisplayName());
        assertEquals("Guinea-Bissau", CountriesEnum.GW.getDisplayName());
        assertEquals("Guyana", CountriesEnum.GY.getDisplayName());
        assertEquals("Haiti", CountriesEnum.HT.getDisplayName());
        assertEquals("Honduras", CountriesEnum.HN.getDisplayName());
        assertEquals("Hong Kong", CountriesEnum.HK.getDisplayName());
        assertEquals("Hungary", CountriesEnum.HU.getDisplayName());
        assertEquals("Iceland", CountriesEnum.IS.getDisplayName());
        assertEquals("India", CountriesEnum.IN.getDisplayName());
        assertEquals("Indonesia", CountriesEnum.ID.getDisplayName());
        assertEquals("Iran", CountriesEnum.IR.getDisplayName());
        assertEquals("Iraq", CountriesEnum.IQ.getDisplayName());
        assertEquals("Ireland", CountriesEnum.IE.getDisplayName());
        assertEquals("Israel", CountriesEnum.IL.getDisplayName());
        assertEquals("Italy", CountriesEnum.IT.getDisplayName());
        assertEquals("Jamaica", CountriesEnum.JM.getDisplayName());
        assertEquals("Japan", CountriesEnum.JP.getDisplayName());
        assertEquals("Jordan", CountriesEnum.JO.getDisplayName());
        assertEquals("Kazakhstan", CountriesEnum.KZ.getDisplayName());
        assertEquals("Kenya", CountriesEnum.KE.getDisplayName());
        assertEquals("Kiribati", CountriesEnum.KI.getDisplayName());
        assertEquals("North Korea", CountriesEnum.KP.getDisplayName());
        assertEquals("South Korea", CountriesEnum.KR.getDisplayName());
        assertEquals("Kosovo", CountriesEnum.XK.getDisplayName());
        assertEquals("Kuwait", CountriesEnum.KW.getDisplayName());
        assertEquals("Kyrgyzstan", CountriesEnum.KG.getDisplayName());
        assertEquals("Laos", CountriesEnum.LA.getDisplayName());
        assertEquals("Latvia", CountriesEnum.LV.getDisplayName());
        assertEquals("Lebanon", CountriesEnum.LB.getDisplayName());
        assertEquals("Lesotho", CountriesEnum.LS.getDisplayName());
        assertEquals("Liberia", CountriesEnum.LR.getDisplayName());
        assertEquals("Libya", CountriesEnum.LY.getDisplayName());
        assertEquals("Liechtenstein", CountriesEnum.LI.getDisplayName());
        assertEquals("Lithuania", CountriesEnum.LT.getDisplayName());
        assertEquals("Luxembourg", CountriesEnum.LU.getDisplayName());
        assertEquals("Macao", CountriesEnum.MO.getDisplayName());
        assertEquals("Madagascar", CountriesEnum.MG.getDisplayName());
        assertEquals("Malawi", CountriesEnum.MW.getDisplayName());
        assertEquals("Malaysia", CountriesEnum.MY.getDisplayName());
        assertEquals("Maldives", CountriesEnum.MV.getDisplayName());
        assertEquals("Mali", CountriesEnum.ML.getDisplayName());
        assertEquals("Malta", CountriesEnum.MT.getDisplayName());
        assertEquals("Marshall Islands", CountriesEnum.MH.getDisplayName());
        assertEquals("Mauritania", CountriesEnum.MR.getDisplayName());
        assertEquals("Mauritius", CountriesEnum.MU.getDisplayName());
        assertEquals("Mexico", CountriesEnum.MX.getDisplayName());
        assertEquals("Micronesia", CountriesEnum.FM.getDisplayName());
        assertEquals("Moldova", CountriesEnum.MD.getDisplayName());
        assertEquals("Monaco", CountriesEnum.MC.getDisplayName());
        assertEquals("Mongolia", CountriesEnum.MN.getDisplayName());
        assertEquals("Montenegro", CountriesEnum.ME.getDisplayName());
        assertEquals("Morocco", CountriesEnum.MA.getDisplayName());
        assertEquals("Mozambique", CountriesEnum.MZ.getDisplayName());
        assertEquals("Myanmar", CountriesEnum.MM.getDisplayName());
        assertEquals("Namibia", CountriesEnum.NA.getDisplayName());
        assertEquals("Nauru", CountriesEnum.NR.getDisplayName());
        assertEquals("Nepal", CountriesEnum.NP.getDisplayName());
        assertEquals("Netherlands", CountriesEnum.NL.getDisplayName());
        assertEquals("New Zealand", CountriesEnum.NZ.getDisplayName());
        assertEquals("Nicaragua", CountriesEnum.NI.getDisplayName());
        assertEquals("Niger", CountriesEnum.NE.getDisplayName());
        assertEquals("Nigeria", CountriesEnum.NG.getDisplayName());
        assertEquals("North Macedonia", CountriesEnum.MK.getDisplayName());
        assertEquals("Norway", CountriesEnum.NO.getDisplayName());
        assertEquals("Oman", CountriesEnum.OM.getDisplayName());
        assertEquals("Pakistan", CountriesEnum.PK.getDisplayName());
        assertEquals("Palau", CountriesEnum.PW.getDisplayName());
        assertEquals("Palestine", CountriesEnum.PS.getDisplayName());
        assertEquals("Panama", CountriesEnum.PA.getDisplayName());
        assertEquals("Papua New Guinea", CountriesEnum.PG.getDisplayName());
        assertEquals("Paraguay", CountriesEnum.PY.getDisplayName());
        assertEquals("Peru", CountriesEnum.PE.getDisplayName());
        assertEquals("Philippines", CountriesEnum.PH.getDisplayName());
        assertEquals("Poland", CountriesEnum.PL.getDisplayName());
        assertEquals("Portugal", CountriesEnum.PT.getDisplayName());
        assertEquals("Puerto Rico", CountriesEnum.PR.getDisplayName());
        assertEquals("Qatar", CountriesEnum.QA.getDisplayName());
        assertEquals("Romania", CountriesEnum.RO.getDisplayName());
        assertEquals("Russia", CountriesEnum.RU.getDisplayName());
        assertEquals("Rwanda", CountriesEnum.RW.getDisplayName());
        assertEquals("Saint Kitts and Nevis", CountriesEnum.KN.getDisplayName());
        assertEquals("Saint Lucia", CountriesEnum.LC.getDisplayName());
        assertEquals("Saint Vincent and the Grenadines", CountriesEnum.VC.getDisplayName());
        assertEquals("Samoa", CountriesEnum.WS.getDisplayName());
        assertEquals("San Marino", CountriesEnum.SM.getDisplayName());
        assertEquals("Sao Tome and Principe", CountriesEnum.ST.getDisplayName());
        assertEquals("Saudi Arabia", CountriesEnum.SA.getDisplayName());
        assertEquals("Senegal", CountriesEnum.SN.getDisplayName());
        assertEquals("Serbia", CountriesEnum.RS.getDisplayName());
        assertEquals("Seychelles", CountriesEnum.SC.getDisplayName());
        assertEquals("Sierra Leone", CountriesEnum.SL.getDisplayName());
        assertEquals("Singapore", CountriesEnum.SG.getDisplayName());
        assertEquals("Slovakia", CountriesEnum.SK.getDisplayName());
        assertEquals("Slovenia", CountriesEnum.SI.getDisplayName());
        assertEquals("Solomon Islands", CountriesEnum.SB.getDisplayName());
        assertEquals("Somalia", CountriesEnum.SO.getDisplayName());
        assertEquals("South Africa", CountriesEnum.ZA.getDisplayName());
        assertEquals("South Sudan", CountriesEnum.SS.getDisplayName());
        assertEquals("Spain", CountriesEnum.ES.getDisplayName());
        assertEquals("Sri Lanka", CountriesEnum.LK.getDisplayName());
        assertEquals("Sudan", CountriesEnum.SD.getDisplayName());
        assertEquals("Suriname", CountriesEnum.SR.getDisplayName());
        assertEquals("Sweden", CountriesEnum.SE.getDisplayName());
        assertEquals("Switzerland", CountriesEnum.CH.getDisplayName());
        assertEquals("Syria", CountriesEnum.SY.getDisplayName());
        assertEquals("Taiwan", CountriesEnum.TW.getDisplayName());
        assertEquals("Tajikistan", CountriesEnum.TJ.getDisplayName());
        assertEquals("Tanzania", CountriesEnum.TZ.getDisplayName());
        assertEquals("Thailand", CountriesEnum.TH.getDisplayName());
        assertEquals("Timor-Leste", CountriesEnum.TL.getDisplayName());
        assertEquals("Togo", CountriesEnum.TG.getDisplayName());
        assertEquals("Tonga", CountriesEnum.TO.getDisplayName());
        assertEquals("Trinidad and Tobago", CountriesEnum.TT.getDisplayName());
        assertEquals("Tunisia", CountriesEnum.TN.getDisplayName());
        assertEquals("Turkey", CountriesEnum.TR.getDisplayName());
        assertEquals("Turkmenistan", CountriesEnum.TM.getDisplayName());
        assertEquals("Tuvalu", CountriesEnum.TV.getDisplayName());
        assertEquals("Uganda", CountriesEnum.UG.getDisplayName());
        assertEquals("Ukraine", CountriesEnum.UA.getDisplayName());
        assertEquals("United Arab Emirates", CountriesEnum.AE.getDisplayName());
        assertEquals("United Kingdom", CountriesEnum.GB.getDisplayName());
        assertEquals("United States of America", CountriesEnum.US.getDisplayName());
        assertEquals("Uruguay", CountriesEnum.UY.getDisplayName());
        assertEquals("Uzbekistan", CountriesEnum.UZ.getDisplayName());
        assertEquals("Vanuatu", CountriesEnum.VU.getDisplayName());
        assertEquals("Venezuela", CountriesEnum.VE.getDisplayName());
        assertEquals("Vietnam", CountriesEnum.VN.getDisplayName());
        assertEquals("Yemen", CountriesEnum.YE.getDisplayName());
        assertEquals("Zambia", CountriesEnum.ZM.getDisplayName());
        assertEquals("Zimbabwe", CountriesEnum.ZW.getDisplayName());
    }



    @Test
    @DisplayName("Test All Codes")
    public void countriesTestingTestAllCodes() {
        assertEquals("AF", CountriesEnum.AF.getCode());
        assertEquals("AL", CountriesEnum.AL.getCode());
        assertEquals("DZ", CountriesEnum.DZ.getCode());
        assertEquals("AD", CountriesEnum.AD.getCode());
        assertEquals("AO", CountriesEnum.AO.getCode());
        assertEquals("AG", CountriesEnum.AG.getCode());
        assertEquals("AR", CountriesEnum.AR.getCode());
        assertEquals("AM", CountriesEnum.AM.getCode());
        assertEquals("AU", CountriesEnum.AU.getCode());
        assertEquals("AT", CountriesEnum.AT.getCode());
        assertEquals("AZ", CountriesEnum.AZ.getCode());
        assertEquals("BS", CountriesEnum.BS.getCode());
        assertEquals("BH", CountriesEnum.BH.getCode());
        assertEquals("BD", CountriesEnum.BD.getCode());
        assertEquals("BB", CountriesEnum.BB.getCode());
        assertEquals("BY", CountriesEnum.BY.getCode());
        assertEquals("BE", CountriesEnum.BE.getCode());
        assertEquals("BZ", CountriesEnum.BZ.getCode());
        assertEquals("BJ", CountriesEnum.BJ.getCode());
        assertEquals("BT", CountriesEnum.BT.getCode());
        assertEquals("BO", CountriesEnum.BO.getCode());
        assertEquals("BA", CountriesEnum.BA.getCode());
        assertEquals("BW", CountriesEnum.BW.getCode());
        assertEquals("BR", CountriesEnum.BR.getCode());
        assertEquals("BN", CountriesEnum.BN.getCode());
        assertEquals("BG", CountriesEnum.BG.getCode());
        assertEquals("BF", CountriesEnum.BF.getCode());
        assertEquals("BI", CountriesEnum.BI.getCode());
        assertEquals("CV", CountriesEnum.CV.getCode());
        assertEquals("KH", CountriesEnum.KH.getCode());
        assertEquals("CM", CountriesEnum.CM.getCode());
        assertEquals("CA", CountriesEnum.CA.getCode());
        assertEquals("CF", CountriesEnum.CF.getCode());
        assertEquals("TD", CountriesEnum.TD.getCode());
        assertEquals("CL", CountriesEnum.CL.getCode());
        assertEquals("CN", CountriesEnum.CN.getCode());
        assertEquals("CO", CountriesEnum.CO.getCode());
        assertEquals("KM", CountriesEnum.KM.getCode());
        assertEquals("CG", CountriesEnum.CG.getCode());
        assertEquals("CD", CountriesEnum.CD.getCode());
        assertEquals("CR", CountriesEnum.CR.getCode());
        assertEquals("CI", CountriesEnum.CI.getCode());
        assertEquals("HR", CountriesEnum.HR.getCode());
        assertEquals("CU", CountriesEnum.CU.getCode());
        assertEquals("CY", CountriesEnum.CY.getCode());
        assertEquals("CZ", CountriesEnum.CZ.getCode());
        assertEquals("DK", CountriesEnum.DK.getCode());
        assertEquals("DJ", CountriesEnum.DJ.getCode());
        assertEquals("DM", CountriesEnum.DM.getCode());
        assertEquals("DO", CountriesEnum.DO.getCode());
        assertEquals("EC", CountriesEnum.EC.getCode());
        assertEquals("EG", CountriesEnum.EG.getCode());
        assertEquals("SV", CountriesEnum.SV.getCode());
        assertEquals("GQ", CountriesEnum.GQ.getCode());
        assertEquals("ER", CountriesEnum.ER.getCode());
        assertEquals("EE", CountriesEnum.EE.getCode());
        assertEquals("SZ", CountriesEnum.SZ.getCode());
        assertEquals("ET", CountriesEnum.ET.getCode());
        assertEquals("FJ", CountriesEnum.FJ.getCode());
        assertEquals("FI", CountriesEnum.FI.getCode());
        assertEquals("FR", CountriesEnum.FR.getCode());
        assertEquals("GA", CountriesEnum.GA.getCode());
        assertEquals("GM", CountriesEnum.GM.getCode());
        assertEquals("GE", CountriesEnum.GE.getCode());
        assertEquals("DE", CountriesEnum.DE.getCode());
        assertEquals("GH", CountriesEnum.GH.getCode());
        assertEquals("GR", CountriesEnum.GR.getCode());
        assertEquals("GD", CountriesEnum.GD.getCode());
        assertEquals("GT", CountriesEnum.GT.getCode());
        assertEquals("GN", CountriesEnum.GN.getCode());
        assertEquals("GW", CountriesEnum.GW.getCode());
        assertEquals("GY", CountriesEnum.GY.getCode());
        assertEquals("HT", CountriesEnum.HT.getCode());
        assertEquals("HN", CountriesEnum.HN.getCode());
        assertEquals("HK", CountriesEnum.HK.getCode());
        assertEquals("HU", CountriesEnum.HU.getCode());
        assertEquals("IS", CountriesEnum.IS.getCode());
        assertEquals("IN", CountriesEnum.IN.getCode());
        assertEquals("ID", CountriesEnum.ID.getCode());
        assertEquals("IR", CountriesEnum.IR.getCode());
        assertEquals("IQ", CountriesEnum.IQ.getCode());
        assertEquals("IE", CountriesEnum.IE.getCode());
        assertEquals("IL", CountriesEnum.IL.getCode());
        assertEquals("IT", CountriesEnum.IT.getCode());
        assertEquals("JM", CountriesEnum.JM.getCode());
        assertEquals("JP", CountriesEnum.JP.getCode());
        assertEquals("JO", CountriesEnum.JO.getCode());
        assertEquals("KZ", CountriesEnum.KZ.getCode());
        assertEquals("KE", CountriesEnum.KE.getCode());
        assertEquals("KI", CountriesEnum.KI.getCode());
        assertEquals("KP", CountriesEnum.KP.getCode());
        assertEquals("KR", CountriesEnum.KR.getCode());
        assertEquals("XK", CountriesEnum.XK.getCode());
        assertEquals("KW", CountriesEnum.KW.getCode());
        assertEquals("KG", CountriesEnum.KG.getCode());
        assertEquals("LA", CountriesEnum.LA.getCode());
        assertEquals("LV", CountriesEnum.LV.getCode());
        assertEquals("LB", CountriesEnum.LB.getCode());
        assertEquals("LS", CountriesEnum.LS.getCode());
        assertEquals("LR", CountriesEnum.LR.getCode());
        assertEquals("LY", CountriesEnum.LY.getCode());
        assertEquals("LI", CountriesEnum.LI.getCode());
        assertEquals("LT", CountriesEnum.LT.getCode());
        assertEquals("LU", CountriesEnum.LU.getCode());
        assertEquals("MO", CountriesEnum.MO.getCode());
        assertEquals("MG", CountriesEnum.MG.getCode());
        assertEquals("MW", CountriesEnum.MW.getCode());
        assertEquals("MY", CountriesEnum.MY.getCode());
        assertEquals("MV", CountriesEnum.MV.getCode());
        assertEquals("ML", CountriesEnum.ML.getCode());
        assertEquals("MT", CountriesEnum.MT.getCode());
        assertEquals("MH", CountriesEnum.MH.getCode());
        assertEquals("MR", CountriesEnum.MR.getCode());
        assertEquals("MU", CountriesEnum.MU.getCode());
        assertEquals("MX", CountriesEnum.MX.getCode());
        assertEquals("FM", CountriesEnum.FM.getCode());
        assertEquals("MD", CountriesEnum.MD.getCode());
        assertEquals("MC", CountriesEnum.MC.getCode());
        assertEquals("MN", CountriesEnum.MN.getCode());
        assertEquals("ME", CountriesEnum.ME.getCode());
        assertEquals("MA", CountriesEnum.MA.getCode());
        assertEquals("MZ", CountriesEnum.MZ.getCode());
        assertEquals("MM", CountriesEnum.MM.getCode());
        assertEquals("NA", CountriesEnum.NA.getCode());
        assertEquals("NR", CountriesEnum.NR.getCode());
        assertEquals("NP", CountriesEnum.NP.getCode());
        assertEquals("NL", CountriesEnum.NL.getCode());
        assertEquals("NZ", CountriesEnum.NZ.getCode());
        assertEquals("NI", CountriesEnum.NI.getCode());
        assertEquals("NE", CountriesEnum.NE.getCode());
        assertEquals("NG", CountriesEnum.NG.getCode());
        assertEquals("MK", CountriesEnum.MK.getCode());
        assertEquals("NO", CountriesEnum.NO.getCode());
        assertEquals("OM", CountriesEnum.OM.getCode());
        assertEquals("PK", CountriesEnum.PK.getCode());
        assertEquals("PW", CountriesEnum.PW.getCode());
        assertEquals("PS", CountriesEnum.PS.getCode());
        assertEquals("PA", CountriesEnum.PA.getCode());
        assertEquals("PG", CountriesEnum.PG.getCode());
        assertEquals("PY", CountriesEnum.PY.getCode());
        assertEquals("PE", CountriesEnum.PE.getCode());
        assertEquals("PH", CountriesEnum.PH.getCode());
        assertEquals("PL", CountriesEnum.PL.getCode());
        assertEquals("PT", CountriesEnum.PT.getCode());
        assertEquals("PR", CountriesEnum.PR.getCode());
        assertEquals("QA", CountriesEnum.QA.getCode());
        assertEquals("RO", CountriesEnum.RO.getCode());
        assertEquals("RU", CountriesEnum.RU.getCode());
        assertEquals("RW", CountriesEnum.RW.getCode());
        assertEquals("KN", CountriesEnum.KN.getCode());
        assertEquals("LC", CountriesEnum.LC.getCode());
        assertEquals("VC", CountriesEnum.VC.getCode());
        assertEquals("WS", CountriesEnum.WS.getCode());
        assertEquals("SM", CountriesEnum.SM.getCode());
        assertEquals("ST", CountriesEnum.ST.getCode());
        assertEquals("SA", CountriesEnum.SA.getCode());
        assertEquals("SN", CountriesEnum.SN.getCode());
        assertEquals("RS", CountriesEnum.RS.getCode());
        assertEquals("SC", CountriesEnum.SC.getCode());
        assertEquals("SL", CountriesEnum.SL.getCode());
        assertEquals("SG", CountriesEnum.SG.getCode());
        assertEquals("SK", CountriesEnum.SK.getCode());
        assertEquals("SI", CountriesEnum.SI.getCode());
        assertEquals("SB", CountriesEnum.SB.getCode());
        assertEquals("SO", CountriesEnum.SO.getCode());
        assertEquals("ZA", CountriesEnum.ZA.getCode());
        assertEquals("SS", CountriesEnum.SS.getCode());
        assertEquals("ES", CountriesEnum.ES.getCode());
        assertEquals("LK", CountriesEnum.LK.getCode());
        assertEquals("SD", CountriesEnum.SD.getCode());
        assertEquals("SR", CountriesEnum.SR.getCode());
        assertEquals("SE", CountriesEnum.SE.getCode());
        assertEquals("CH", CountriesEnum.CH.getCode());
        assertEquals("SY", CountriesEnum.SY.getCode());
        assertEquals("TW", CountriesEnum.TW.getCode());
        assertEquals("TJ", CountriesEnum.TJ.getCode());
        assertEquals("TZ", CountriesEnum.TZ.getCode());
        assertEquals("TH", CountriesEnum.TH.getCode());
        assertEquals("TL", CountriesEnum.TL.getCode());
        assertEquals("TG", CountriesEnum.TG.getCode());
        assertEquals("TO", CountriesEnum.TO.getCode());
        assertEquals("TT", CountriesEnum.TT.getCode());
        assertEquals("TN", CountriesEnum.TN.getCode());
        assertEquals("TR", CountriesEnum.TR.getCode());
        assertEquals("TM", CountriesEnum.TM.getCode());
        assertEquals("TV", CountriesEnum.TV.getCode());
        assertEquals("UG", CountriesEnum.UG.getCode());
        assertEquals("UA", CountriesEnum.UA.getCode());
        assertEquals("AE", CountriesEnum.AE.getCode());
        assertEquals("GB", CountriesEnum.GB.getCode());
        assertEquals("US", CountriesEnum.US.getCode());
        assertEquals("UY", CountriesEnum.UY.getCode());
        assertEquals("UZ", CountriesEnum.UZ.getCode());
        assertEquals("VU", CountriesEnum.VU.getCode());
        assertEquals("VE", CountriesEnum.VE.getCode());
        assertEquals("VN", CountriesEnum.VN.getCode());
        assertEquals("YE", CountriesEnum.YE.getCode());
        assertEquals("ZM", CountriesEnum.ZM.getCode());
        assertEquals("ZW", CountriesEnum.ZW.getCode());
    }

    @Test
    @DisplayName("Test Invalid Fetch")
    public void countriesTestingTestInValidFetch() {
        assertThrows( IllegalArgumentException.class, () -> {
            CountriesEnum.fromCode("ZZ");
        } );
    }

    @Test
    @DisplayName("Test fromCode")
    public void countriesTestingTestFromCode() {
        assertEquals(CountriesEnum.AF, CountriesEnum.fromCode("AF"));
        assertEquals(CountriesEnum.AL, CountriesEnum.fromCode("AL"));
        assertEquals(CountriesEnum.DZ, CountriesEnum.fromCode("DZ"));
        assertEquals(CountriesEnum.AD, CountriesEnum.fromCode("AD"));
        assertEquals(CountriesEnum.AO, CountriesEnum.fromCode("AO"));
        assertEquals(CountriesEnum.AG, CountriesEnum.fromCode("AG"));
        assertEquals(CountriesEnum.AR, CountriesEnum.fromCode("AR"));
        assertEquals(CountriesEnum.AM, CountriesEnum.fromCode("AM"));
        assertEquals(CountriesEnum.AU, CountriesEnum.fromCode("AU"));
        assertEquals(CountriesEnum.AT, CountriesEnum.fromCode("AT"));
        assertEquals(CountriesEnum.AZ, CountriesEnum.fromCode("AZ"));
        assertEquals(CountriesEnum.BS, CountriesEnum.fromCode("BS"));
        assertEquals(CountriesEnum.BH, CountriesEnum.fromCode("BH"));
        assertEquals(CountriesEnum.BD, CountriesEnum.fromCode("BD"));
        assertEquals(CountriesEnum.BB, CountriesEnum.fromCode("BB"));
        assertEquals(CountriesEnum.BY, CountriesEnum.fromCode("BY"));
        assertEquals(CountriesEnum.BE, CountriesEnum.fromCode("BE"));
        assertEquals(CountriesEnum.BZ, CountriesEnum.fromCode("BZ"));
        assertEquals(CountriesEnum.BJ, CountriesEnum.fromCode("BJ"));
        assertEquals(CountriesEnum.BT, CountriesEnum.fromCode("BT"));
        assertEquals(CountriesEnum.BO, CountriesEnum.fromCode("BO"));
        assertEquals(CountriesEnum.BA, CountriesEnum.fromCode("BA"));
        assertEquals(CountriesEnum.BW, CountriesEnum.fromCode("BW"));
        assertEquals(CountriesEnum.BR, CountriesEnum.fromCode("BR"));
        assertEquals(CountriesEnum.BN, CountriesEnum.fromCode("BN"));
        assertEquals(CountriesEnum.BG, CountriesEnum.fromCode("BG"));
        assertEquals(CountriesEnum.BF, CountriesEnum.fromCode("BF"));
        assertEquals(CountriesEnum.BI, CountriesEnum.fromCode("BI"));
        assertEquals(CountriesEnum.CV, CountriesEnum.fromCode("CV"));
        assertEquals(CountriesEnum.KH, CountriesEnum.fromCode("KH"));
        assertEquals(CountriesEnum.CM, CountriesEnum.fromCode("CM"));
        assertEquals(CountriesEnum.CA, CountriesEnum.fromCode("CA"));
        assertEquals(CountriesEnum.CF, CountriesEnum.fromCode("CF"));
        assertEquals(CountriesEnum.TD, CountriesEnum.fromCode("TD"));
        assertEquals(CountriesEnum.CL, CountriesEnum.fromCode("CL"));
        assertEquals(CountriesEnum.CN, CountriesEnum.fromCode("CN"));
        assertEquals(CountriesEnum.CO, CountriesEnum.fromCode("CO"));
        assertEquals(CountriesEnum.KM, CountriesEnum.fromCode("KM"));
        assertEquals(CountriesEnum.CG, CountriesEnum.fromCode("CG"));
        assertEquals(CountriesEnum.CD, CountriesEnum.fromCode("CD"));
        assertEquals(CountriesEnum.CR, CountriesEnum.fromCode("CR"));
        assertEquals(CountriesEnum.CI, CountriesEnum.fromCode("CI"));
        assertEquals(CountriesEnum.HR, CountriesEnum.fromCode("HR"));
        assertEquals(CountriesEnum.CU, CountriesEnum.fromCode("CU"));
        assertEquals(CountriesEnum.CY, CountriesEnum.fromCode("CY"));
        assertEquals(CountriesEnum.CZ, CountriesEnum.fromCode("CZ"));
        assertEquals(CountriesEnum.DK, CountriesEnum.fromCode("DK"));
        assertEquals(CountriesEnum.DJ, CountriesEnum.fromCode("DJ"));
        assertEquals(CountriesEnum.DM, CountriesEnum.fromCode("DM"));
        assertEquals(CountriesEnum.DO, CountriesEnum.fromCode("DO"));
        assertEquals(CountriesEnum.EC, CountriesEnum.fromCode("EC"));
        assertEquals(CountriesEnum.EG, CountriesEnum.fromCode("EG"));
        assertEquals(CountriesEnum.SV, CountriesEnum.fromCode("SV"));
        assertEquals(CountriesEnum.GQ, CountriesEnum.fromCode("GQ"));
        assertEquals(CountriesEnum.ER, CountriesEnum.fromCode("ER"));
        assertEquals(CountriesEnum.EE, CountriesEnum.fromCode("EE"));
        assertEquals(CountriesEnum.SZ, CountriesEnum.fromCode("SZ"));
        assertEquals(CountriesEnum.ET, CountriesEnum.fromCode("ET"));
        assertEquals(CountriesEnum.FJ, CountriesEnum.fromCode("FJ"));
        assertEquals(CountriesEnum.FI, CountriesEnum.fromCode("FI"));
        assertEquals(CountriesEnum.FR, CountriesEnum.fromCode("FR"));
        assertEquals(CountriesEnum.GA, CountriesEnum.fromCode("GA"));
        assertEquals(CountriesEnum.GM, CountriesEnum.fromCode("GM"));
        assertEquals(CountriesEnum.GE, CountriesEnum.fromCode("GE"));
        assertEquals(CountriesEnum.DE, CountriesEnum.fromCode("DE"));
        assertEquals(CountriesEnum.GH, CountriesEnum.fromCode("GH"));
        assertEquals(CountriesEnum.GR, CountriesEnum.fromCode("GR"));
        assertEquals(CountriesEnum.GD, CountriesEnum.fromCode("GD"));
        assertEquals(CountriesEnum.GT, CountriesEnum.fromCode("GT"));
        assertEquals(CountriesEnum.GN, CountriesEnum.fromCode("GN"));
        assertEquals(CountriesEnum.GW, CountriesEnum.fromCode("GW"));
        assertEquals(CountriesEnum.GY, CountriesEnum.fromCode("GY"));
        assertEquals(CountriesEnum.HT, CountriesEnum.fromCode("HT"));
        assertEquals(CountriesEnum.HN, CountriesEnum.fromCode("HN"));
        assertEquals(CountriesEnum.HK, CountriesEnum.fromCode("HK"));
        assertEquals(CountriesEnum.HU, CountriesEnum.fromCode("HU"));
        assertEquals(CountriesEnum.IS, CountriesEnum.fromCode("IS"));
        assertEquals(CountriesEnum.IN, CountriesEnum.fromCode("IN"));
        assertEquals(CountriesEnum.ID, CountriesEnum.fromCode("ID"));
        assertEquals(CountriesEnum.IR, CountriesEnum.fromCode("IR"));
        assertEquals(CountriesEnum.IQ, CountriesEnum.fromCode("IQ"));
        assertEquals(CountriesEnum.IE, CountriesEnum.fromCode("IE"));
        assertEquals(CountriesEnum.IL, CountriesEnum.fromCode("IL"));
        assertEquals(CountriesEnum.IT, CountriesEnum.fromCode("IT"));
        assertEquals(CountriesEnum.JM, CountriesEnum.fromCode("JM"));
        assertEquals(CountriesEnum.JP, CountriesEnum.fromCode("JP"));
        assertEquals(CountriesEnum.JO, CountriesEnum.fromCode("JO"));
        assertEquals(CountriesEnum.KZ, CountriesEnum.fromCode("KZ"));
        assertEquals(CountriesEnum.KE, CountriesEnum.fromCode("KE"));
        assertEquals(CountriesEnum.KI, CountriesEnum.fromCode("KI"));
        assertEquals(CountriesEnum.KP, CountriesEnum.fromCode("KP"));
        assertEquals(CountriesEnum.KR, CountriesEnum.fromCode("KR"));
        assertEquals(CountriesEnum.XK, CountriesEnum.fromCode("XK"));
        assertEquals(CountriesEnum.KW, CountriesEnum.fromCode("KW"));
        assertEquals(CountriesEnum.KG, CountriesEnum.fromCode("KG"));
        assertEquals(CountriesEnum.LA, CountriesEnum.fromCode("LA"));
        assertEquals(CountriesEnum.LV, CountriesEnum.fromCode("LV"));
        assertEquals(CountriesEnum.LB, CountriesEnum.fromCode("LB"));
        assertEquals(CountriesEnum.LS, CountriesEnum.fromCode("LS"));
        assertEquals(CountriesEnum.LR, CountriesEnum.fromCode("LR"));
        assertEquals(CountriesEnum.LY, CountriesEnum.fromCode("LY"));
        assertEquals(CountriesEnum.LI, CountriesEnum.fromCode("LI"));
        assertEquals(CountriesEnum.LT, CountriesEnum.fromCode("LT"));
        assertEquals(CountriesEnum.LU, CountriesEnum.fromCode("LU"));
        assertEquals(CountriesEnum.MO, CountriesEnum.fromCode("MO"));
        assertEquals(CountriesEnum.MG, CountriesEnum.fromCode("MG"));
        assertEquals(CountriesEnum.MW, CountriesEnum.fromCode("MW"));
        assertEquals(CountriesEnum.MY, CountriesEnum.fromCode("MY"));
        assertEquals(CountriesEnum.MV, CountriesEnum.fromCode("MV"));
        assertEquals(CountriesEnum.ML, CountriesEnum.fromCode("ML"));
        assertEquals(CountriesEnum.MT, CountriesEnum.fromCode("MT"));
        assertEquals(CountriesEnum.MH, CountriesEnum.fromCode("MH"));
        assertEquals(CountriesEnum.MR, CountriesEnum.fromCode("MR"));
        assertEquals(CountriesEnum.MU, CountriesEnum.fromCode("MU"));
        assertEquals(CountriesEnum.MX, CountriesEnum.fromCode("MX"));
        assertEquals(CountriesEnum.FM, CountriesEnum.fromCode("FM"));
        assertEquals(CountriesEnum.MD, CountriesEnum.fromCode("MD"));
        assertEquals(CountriesEnum.MC, CountriesEnum.fromCode("MC"));
        assertEquals(CountriesEnum.MN, CountriesEnum.fromCode("MN"));
        assertEquals(CountriesEnum.ME, CountriesEnum.fromCode("ME"));
        assertEquals(CountriesEnum.MA, CountriesEnum.fromCode("MA"));
        assertEquals(CountriesEnum.MZ, CountriesEnum.fromCode("MZ"));
        assertEquals(CountriesEnum.MM, CountriesEnum.fromCode("MM"));
        assertEquals(CountriesEnum.NA, CountriesEnum.fromCode("NA"));
        assertEquals(CountriesEnum.NR, CountriesEnum.fromCode("NR"));
        assertEquals(CountriesEnum.NP, CountriesEnum.fromCode("NP"));
        assertEquals(CountriesEnum.NL, CountriesEnum.fromCode("NL"));
        assertEquals(CountriesEnum.NZ, CountriesEnum.fromCode("NZ"));
        assertEquals(CountriesEnum.NI, CountriesEnum.fromCode("NI"));
        assertEquals(CountriesEnum.NE, CountriesEnum.fromCode("NE"));
        assertEquals(CountriesEnum.NG, CountriesEnum.fromCode("NG"));
        assertEquals(CountriesEnum.MK, CountriesEnum.fromCode("MK"));
        assertEquals(CountriesEnum.NO, CountriesEnum.fromCode("NO"));
        assertEquals(CountriesEnum.OM, CountriesEnum.fromCode("OM"));
        assertEquals(CountriesEnum.PK, CountriesEnum.fromCode("PK"));
        assertEquals(CountriesEnum.PW, CountriesEnum.fromCode("PW"));
        assertEquals(CountriesEnum.PS, CountriesEnum.fromCode("PS"));
        assertEquals(CountriesEnum.PA, CountriesEnum.fromCode("PA"));
        assertEquals(CountriesEnum.PG, CountriesEnum.fromCode("PG"));
        assertEquals(CountriesEnum.PY, CountriesEnum.fromCode("PY"));
        assertEquals(CountriesEnum.PE, CountriesEnum.fromCode("PE"));
        assertEquals(CountriesEnum.PH, CountriesEnum.fromCode("PH"));
        assertEquals(CountriesEnum.PL, CountriesEnum.fromCode("PL"));
        assertEquals(CountriesEnum.PT, CountriesEnum.fromCode("PT"));
        assertEquals(CountriesEnum.PR, CountriesEnum.fromCode("PR"));
        assertEquals(CountriesEnum.QA, CountriesEnum.fromCode("QA"));
        assertEquals(CountriesEnum.RO, CountriesEnum.fromCode("RO"));
        assertEquals(CountriesEnum.RU, CountriesEnum.fromCode("RU"));
        assertEquals(CountriesEnum.RW, CountriesEnum.fromCode("RW"));
        assertEquals(CountriesEnum.KN, CountriesEnum.fromCode("KN"));
        assertEquals(CountriesEnum.LC, CountriesEnum.fromCode("LC"));
        assertEquals(CountriesEnum.VC, CountriesEnum.fromCode("VC"));
        assertEquals(CountriesEnum.WS, CountriesEnum.fromCode("WS"));
        assertEquals(CountriesEnum.SM, CountriesEnum.fromCode("SM"));
        assertEquals(CountriesEnum.ST, CountriesEnum.fromCode("ST"));
        assertEquals(CountriesEnum.SA, CountriesEnum.fromCode("SA"));
        assertEquals(CountriesEnum.SN, CountriesEnum.fromCode("SN"));
        assertEquals(CountriesEnum.RS, CountriesEnum.fromCode("RS"));
        assertEquals(CountriesEnum.SC, CountriesEnum.fromCode("SC"));
        assertEquals(CountriesEnum.SL, CountriesEnum.fromCode("SL"));
        assertEquals(CountriesEnum.SG, CountriesEnum.fromCode("SG"));
        assertEquals(CountriesEnum.SK, CountriesEnum.fromCode("SK"));
        assertEquals(CountriesEnum.SI, CountriesEnum.fromCode("SI"));
        assertEquals(CountriesEnum.SB, CountriesEnum.fromCode("SB"));
        assertEquals(CountriesEnum.SO, CountriesEnum.fromCode("SO"));
        assertEquals(CountriesEnum.ZA, CountriesEnum.fromCode("ZA"));
        assertEquals(CountriesEnum.SS, CountriesEnum.fromCode("SS"));
        assertEquals(CountriesEnum.ES, CountriesEnum.fromCode("ES"));
        assertEquals(CountriesEnum.LK, CountriesEnum.fromCode("LK"));
        assertEquals(CountriesEnum.SD, CountriesEnum.fromCode("SD"));
        assertEquals(CountriesEnum.SR, CountriesEnum.fromCode("SR"));
        assertEquals(CountriesEnum.SE, CountriesEnum.fromCode("SE"));
        assertEquals(CountriesEnum.CH, CountriesEnum.fromCode("CH"));
        assertEquals(CountriesEnum.SY, CountriesEnum.fromCode("SY"));
        assertEquals(CountriesEnum.TW, CountriesEnum.fromCode("TW"));
        assertEquals(CountriesEnum.TJ, CountriesEnum.fromCode("TJ"));
        assertEquals(CountriesEnum.TZ, CountriesEnum.fromCode("TZ"));
        assertEquals(CountriesEnum.TH, CountriesEnum.fromCode("TH"));
        assertEquals(CountriesEnum.TL, CountriesEnum.fromCode("TL"));
        assertEquals(CountriesEnum.TG, CountriesEnum.fromCode("TG"));
        assertEquals(CountriesEnum.TO, CountriesEnum.fromCode("TO"));
        assertEquals(CountriesEnum.TT, CountriesEnum.fromCode("TT"));
        assertEquals(CountriesEnum.TN, CountriesEnum.fromCode("TN"));
        assertEquals(CountriesEnum.TR, CountriesEnum.fromCode("TR"));
        assertEquals(CountriesEnum.TM, CountriesEnum.fromCode("TM"));
        assertEquals(CountriesEnum.TV, CountriesEnum.fromCode("TV"));
        assertEquals(CountriesEnum.UG, CountriesEnum.fromCode("UG"));
        assertEquals(CountriesEnum.UA, CountriesEnum.fromCode("UA"));
        assertEquals(CountriesEnum.AE, CountriesEnum.fromCode("AE"));
        assertEquals(CountriesEnum.GB, CountriesEnum.fromCode("GB"));
        assertEquals(CountriesEnum.US, CountriesEnum.fromCode("US"));
        assertEquals(CountriesEnum.UY, CountriesEnum.fromCode("UY"));
        assertEquals(CountriesEnum.UZ, CountriesEnum.fromCode("UZ"));
        assertEquals(CountriesEnum.VU, CountriesEnum.fromCode("VU"));
        assertEquals(CountriesEnum.VE, CountriesEnum.fromCode("VE"));
        assertEquals(CountriesEnum.VN, CountriesEnum.fromCode("VN"));
        assertEquals(CountriesEnum.YE, CountriesEnum.fromCode("YE"));
        assertEquals(CountriesEnum.ZM, CountriesEnum.fromCode("ZM"));
        assertEquals(CountriesEnum.ZW, CountriesEnum.fromCode("ZW"));
    }
}

